### PR TITLE
update html and CSS for alert

### PR DESCRIPTION
**Pull request by aniketsingh13**
https://user-images.githubusercontent.com/85512784/153145708-09133e99-fb52-4197-b590-ef5c97bbaa3b.png

### CODE REVIEW

**Review by maitrakhatri — APPROVED** [review]
looks good to me

**Review by shubhamkumar648 — COMMENTED** [review]
as i see your code looks good to me but yoy not align proprly ! remove unnecessary space in html file

**Comment by aniketsingh13** [comment]
> as i see your code looks good to me but yoy not align proprly ! remove unnecessary space in html file

thanks i will considerd the chnages

**Comment by aniketsingh13** [comment]
> > as i see your code looks good to me but yoy not align proprly ! remove unnecessary space in html file
> 
> thanks i will considerd the changes and will update it in next commit

**Review by shubhamkumar648 — APPROVED** [review]
ok after commit , then you can merge

**Pull request merged**
